name: Release Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Build UI
        run: bun --bun run release-build

      - name: Archive output build
        uses: actions/upload-artifact@v2
        with:
          name: ui-build
          path: out/

  release:
    if: github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Get version from package.json
        id: version
        run: echo $(cat ${PACKAGE_JSON_PATH}/package.json | jq '.version' | tr -d '"') >> $GITHUB_OUTPUT

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ui-build

      - name: Create Github Release
        id: github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          draft: true
          prerelease: true

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/marahuyo-ui.${{ steps.version.outputs.VERSION }}.min.css
          asset_name: marahuyo-ui.${{ steps.version.outputs.VERSION }}.min.css
          asset_content_type: text/css
